# Generated by Django 6.0.7 on 2026-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_id', models.CharField(max_length=100)),
                ('voice_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='generated_voices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
